### ISSUE TITLE
Stuck in 'aborting' state

### ISSUE THREAD

**Issue by fikkatra** [fenivana/pull-to-refresh#1]
I noticed that sometimes the library gets stuck in the 'aborting' state. This happens when, instead of letting go after pulling down, you drag your finger all the way back up. I noticed this behavior when using the ios styling (haven't tested with other styles). 

Debugging revealed that the `transitionend` event in the `aborting` function (in animates.js) doesn't always fire:

```
  elMain.addEventListener('transitionend', function () {
	// sometimes, this code does not get executed
	elMain.style.transition = '';
	resolve();
  });
```

The promise in pullToRefresh.js does not resolve and the state is not reset:

```
animates.aborting(opts).then(function () {
  removeClass(state);
  distance = state = offset = null;
  onStateChange(state);
});
```

The spinner keeps on showing and it is also not possible to pull to refresh, causing the app to be 'stuck' in the aborting state.

**Comment by jiangfengming** [comment]
Thanks for reporting.
