### ISSUE TITLE
undefined is not an object(evaluating 'this.state')

### ISSUE THREAD

**Issue by hzl123456** [fenivana/pull-to-refresh#6]
pullToRefresh({
      container: document.querySelector('.container'),
      animates: ptrAnimatesMaterial,
      refresh() {
        return new Promise(resolve => {
          let a = this.state.data
          setTimeout(resolve, 2000)
        })
      }
    }).bind(this)

**Comment by jiangfengming** [comment]
It's not a lib's bug, it's your syntax issue.

```js
pullToRefresh({
  container: document.querySelector('.container'),
  animates: ptrAnimatesMaterial,
  refresh: () => {  // <--- use arrow function
    return new Promise(resolve => {
      let a = this.state.data
      setTimeout(resolve, 2000)
    })
  }
})
```
